BOCA = {"Equipo": "Boca",
        "Provincia": "CABA",
        "Libertadores": 6,
        "Descensos": 0,
        "Apodo": "Xeneize",
        "Titulos_Locales": 52,
        "Titulos_Internacionales": 18,
        "Jugadores_Importantes": ["Benedetto", "Maradona", "Zarate", "Caniggia", "Pratto"],
        "Rival": "River",
        "Color": ["Azul", "Amarillo"],
        "Marca": "Adidas",
        "Cuatro_Grandes": True}

RIVER = {"Equipo": "River",
        "Provincia": "CABA",
        "Libertadores": 4,
        "Descensos": 1,
        "Apodo": "Millonario",
        "Titulos_Locales": 52,
        "Titulos_Internacionales": 12,
        "Rival": "Boca",
        "Color": ["Blanco", "Rojo"],
        "Marca": "Adidas",
        "Cuatro_Grandes": True}

RACING = {"Equipo": "Racing",
        "Provincia": "CABA",
        "Libertadores": 1,
        "Descensos": 1,
        "Apodo": "La Academia",
        "Titulos_Locales": 33,
        "Titulos_Internacionales": 6,
        "Rival": "Independiente",
        "Color": ["Blanco", "Celeste"],
        "Marca": "Kappa",
        "Cuatro_Grandes": True}

INDEPENDIENTE = {"Equipo": "Independiente",
        "Provincia": "CABA",
        "Libertadores": 7,
        "Descensos": 1,
        "Apodo": "El Rojo",
        "Titulos_Locales": 25,
        "Titulos_Internacionales": 18,
        "Rival": "Racing",
        "Color": ["Blanco", "Rojo"],
        "Marca": "Puma",
        "Cuatro_Grandes": True}

SAN_LORENZO = {"Equipo": "San Lorenzo",
        "Provincia": "CABA",
        "Libertadores": 1,
        "Descensos": 1,
        "Apodo": "Cuervo",
        "Titulos_Locales": 17,
        "Titulos_Internacionales": 3,
        "Rival": "Huracan",
        "Color": ["Azul", "Rojo"],
        "Marca": "Nike",
        "Cuatro_Grandes": False}

VELEZ = {"Equipo": "Velez",
        "Provincia": "CABA",
        "Libertadores": 1,
        "Descensos": 1,
        "Apodo": "Fortín",
        "Titulos_Locales": 11,
        "Titulos_Internacionales": 3,
        "Rival": False,
        "Color": ["Azul", "Blanco"],
        "Marca": "Diadora",
        "Cuatro_Grandes": False}

ESTUDIANTES = {"Equipo": "Estudiantes de La Plata",
        "Provincia": "Buenos Aires",
        "Libertadores": 4,
        "Descensos": 2,
        "Apodo": "Pincharrata",
        "Titulos_Locales": 8,
        "Titulos_Internacionales": 6,
        "Rival": "Gimnasia",
        "Color": ["Rojo", "Blanco"],
        "Marca": "Diadora",
        "Cuatro_Grandes": False}

TALLERES = {"Equipo": "Talleres",
        "Provincia": "Cordoba",
        "Libertadores": 0,
        "Descensos": 4,
        "Apodo": "La T",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 1,
        "Rival": "Belgrano",
        "Color": ["Azul", "Blanco"],
        "Marca": "GIVOVA",
        "Cuatro_Grandes": False}

LANUS = {"Equipo": "Lanus",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 6,
        "Apodo": "Granate",
        "Titulos_Locales": 4,
        "Titulos_Internacionales": 2,
        "Rival": "Banfield",
        "Color": ["Bordo"],
        "Marca": "Errea",
        "Cuatro_Grandes": False}

DEFENSA = {"Equipo": "Defensa y Justicia",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 0,
        "Apodo": "El Halcón",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 2,
        "Rival": "Arsenal",
        "Color": ["Amarillo", "Verde"],
        "Marca": "Lyon",
        "Cuatro_Grandes": False}

ROSARIO = {"Equipo": "Rosario Central",
        "Provincia": "Santa Fe",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Canalla",
        "Titulos_Locales": 10,
        "Titulos_Internacionales": 1,
        "Rival": "Newells",
        "Color": ["Azul", "Amarillo"],
        "Marca": "Diadora",
        "Cuatro_Grandes": False}

GODOY_CRUZ = {"Equipo": "Godoy Cruz",
        "Provincia": "Mendoza",
        "Libertadores": 0,
        "Descensos": 3,
        "Apodo": "Tomba",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Azul", "Blanco"],
        "Marca": "Fiume",
        "Cuatro_Grandes": False}

ARGENTINOS_JUNIORS = {"Equipo": "Argentinos Juniors",
        "Provincia": "CABA",
        "Libertadores": 1,
        "Descensos": 5,
        "Apodo": "El Bicho",
        "Titulos_Locales": 3,
        "Titulos_Internacionales": 2,
        "Rival": "Platense",
        "Color": ["Rojo", "Blanco"],
        "Marca": "Umbro",
        "Cuatro_Grandes": False}

BELGRANO = {"Equipo": "Belgrano",
        "Provincia": "Córdoba",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Pirata",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": "Talleres",
        "Color": ["Celeste"],
        "Marca": "Errea",
        "Cuatro_Grandes": False}

NEWELLS = {"Equipo": "Newells",
        "Provincia": "Santa Fe",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "La Lepra",
        "Titulos_Locales": 9,
        "Titulos_Internacionales": 0,
        "Rival": "Rosario Central",
        "Color": ["Negro", "Rojo"],
        "Marca": "Givova",
        "Cuatro_Grandes": False}

BARRACAS = {"Equipo": "Barracas Central",
        "Provincia": "CABA",
        "Libertadores": 0,
        "Descensos": 0,
        "Apodo": "El Guapo",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Rojo", "Blanco"],
        "Marca": "Il Ossso",
        "Cuatro_Grandes": False}

TIGRE = {"Equipo": "Tigre",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Matadores",
        "Titulos_Locales": 1,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Azul", "Rojo"],
        "Marca": "Kappa",
        "Cuatro_Grandes": False}

PLATENSE = {"Equipo": "Platense",
        "Provincia": "CABA",
        "Libertadores": 0,
        "Descensos": 4,
        "Apodo": "El Calamar",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": "Argentinos Juniors",
        "Color": ["Bordo", "Blanco"],
        "Marca": "Hummel",
        "Cuatro_Grandes": False}

INSTITUTO = {"Equipo": "Instituto",
        "Provincia": "Cordoba",
        "Libertadores": 0,
        "Descensos": 2,
        "Apodo": "El Glorioso",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": "Belgrano",
        "Color": ["Rojo", "Blanco"],
        "Marca": "Lyon",
        "Cuatro_Grandes": False}

SARMIENTO = {"Equipo": "Sarmiento",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 2,
        "Apodo": "Verdes",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Verde"],
        "Marca": "Coach",
        "Cuatro_Grandes": False}

UNION = {"Equipo": "Union",
        "Provincia": "Santa Fe",
        "Libertadores": 0,
        "Descensos": 6,
        "Apodo": "Tatengue",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": "Colon",
        "Color": ["Rojo", "Blanco"],
        "Marca": "Kappa",
        "Cuatro_Grandes": False}

BANFIELD = {"Equipo": "Banfield",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 7,
        "Apodo": "Taladro",
        "Titulos_Locales": 2,
        "Titulos_Internacionales": 0,
        "Rival": "Lanus",
        "Color": ["Verde", "Blanco"],
        "Marca": "Athix",
        "Cuatro_Grandes": False}

GIMNASIA = {"Equipo": "Gimnasia",
        "Provincia": "Buenos Aires",
        "Libertadores": 0,
        "Descensos": 5,
        "Apodo": "El Lobo",
        "Titulos_Locales": 2,
        "Titulos_Internacionales": 0,
        "Rival": "Estudiantes de La Plata",
        "Color": ["Azul", "Blanco"],
        "Marca": "Givova",
        "Cuatro_Grandes": False}

CENTRAL_CORDOBA = {"Equipo": "Central Cordoba",
        "Provincia": "Santiago del Estero",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Ferroviario",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Negro", "Blanco"],
        "Marca": "Adhoc",
        "Cuatro_Grandes": False}

HURACAN = {"Equipo": "Huracan",
        "Provincia": "CABA",
        "Libertadores": 0,
        "Descensos": 4,
        "Apodo": "Quemero",
        "Titulos_Locales": 13,
        "Titulos_Internacionales": 0,
        "Rival": "San Lorenzo",
        "Color": ["Blanco"],
        "Marca": "Peak",
        "Cuatro_Grandes": False}

COLON = {"Equipo": "Colon",
        "Provincia": "Santa Fe",
        "Libertadores": 0,
        "Descensos": 2,
        "Apodo": "Sabalero",
        "Titulos_Locales": 1,
        "Titulos_Internacionales": 0,
        "Rival": "Union",
        "Color": ["Negro", "Rojo"],
        "Marca": "Kelme",
        "Cuatro_Grandes": False}

ARSENAL = {"Equipo": "Arsenal",
        "Provincia": "CABA",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Arse",
        "Titulos_Locales": 3,
        "Titulos_Internacionales": 2,
        "Rival": False,
        "Color": ["Celeste", "Rojo"],
        "Marca": "Diadora",
        "Cuatro_Grandes": False}

ATLETICO_TUCUMAN = {"Equipo": "Atletico Tucuman",
        "Provincia": "Tucuman",
        "Libertadores": 0,
        "Descensos": 1,
        "Apodo": "Decano",
        "Titulos_Locales": 0,
        "Titulos_Internacionales": 0,
        "Rival": False,
        "Color": ["Celeste", "Blanco"],
        "Marca": "Umbro",
        "Cuatro_Grandes": False}

PRIMERA_NACIONAL = [RIVER, TALLERES, SAN_LORENZO, LANUS, ESTUDIANTES, DEFENSA, BOCA, ROSARIO, GODOY_CRUZ, ARGENTINOS_JUNIORS, ATLETICO_TUCUMAN, RACING, BELGRANO, NEWELLS, BARRACAS, TIGRE, PLATENSE, INSTITUTO, SARMIENTO, UNION, BANFIELD, GIMNASIA, CENTRAL_CORDOBA, INDEPENDIENTE, VELEZ, HURACAN, COLON, ARSENAL]
